In [ ]:
pip install --upgrade yfinance

Requirement already satisfied: yfinance in /usr/local/lib/python3.11/dist-packages (0.2.54)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.11/dist-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.11/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from yfinance) (4.3.6)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2025.1)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.11/dist-packages (from yfinance) (2.4.6)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.11/dist-packages (from yfinance) (3.17.9)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.11/dist-packages (from yfinance) (4.13.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.6)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.11/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.12.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas>=1.3.0->yfinance) (2025.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.31->yfinance) (2025.1.31)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)

In [1]:
import pandas as pd
import ast
import matplotlib.pyplot as plt
import numpy as np

In [2]:
def prepare_sentiment_data(company_name):
  from google.colab import drive

  drive.mount('/content/gdrive')

  news_data = pd.read_excel(r"/content/gdrive/My Drive/Dataset/News_Info.xlsx",sheet_name=company_name)
  news_data['date']=pd.to_datetime(news_data['date']).dt.date

  news_data.dropna(inplace=True)
  news_data['sentiment'] = news_data['sentiment'].apply(ast.literal_eval)
  news_data['polarity score'] = news_data['sentiment'].apply(lambda x: x.get('polarity'))

  polarity = news_data.groupby('date')['polarity score'].mean()
  polarity = pd.DataFrame(polarity)
  polarity = polarity.rename(columns={'polarity score':company_name+'_polarity'})

  return polarity

In [3]:
def prepare_sentiment_data_2(company_name):
  from google.colab import drive

  drive.mount('/content/gdrive')

  news_data = pd.read_excel(r"/content/gdrive/My Drive/Dataset/News_Info_part3.xlsx",sheet_name=company_name)
  news_data['date']=pd.to_datetime(news_data['date']).dt.date

  news_data.dropna(inplace=True)
  news_data['sentiment'] = news_data['sentiment'].apply(ast.literal_eval)
  news_data['polarity score'] = news_data['sentiment'].apply(lambda x: x.get('polarity'))

  polarity = news_data.groupby('date')['polarity score'].mean()
  polarity = pd.DataFrame(polarity)
  polarity = polarity.rename(columns={'polarity score':company_name+'_polarity'})

  return polarity

In [4]:
hsbc_polarity = prepare_sentiment_data_2('HSBC')
hsbc_polarity

Mounted at /content/gdrive

            HSBC_polarity
date
2021-03-25         0.5520
2021-03-26         0.9465
2021-03-31         0.9840
2021-04-01         0.9730
2021-04-03         0.9260
...                   ...
2024-05-02         0.9700
2024-05-03         0.9865
2024-05-04         0.1495
2024-05-06         0.9980
2024-05-08         0.9980

[619 rows x 1 columns]

In [5]:
ubs_polarity = prepare_sentiment_data_2('UBS')
ubs_polarity

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

            UBS_polarity
date
2018-03-27      0.997000
2018-05-25      0.710000
2018-06-07      0.994000
2018-06-13      0.000000
2018-11-26     -0.586000
...                  ...
2024-05-02      0.999000
2024-05-03      0.995200
2024-05-06      0.841000
2024-05-07      0.580500
2024-05-08      0.424333

[697 rows x 1 columns]

In [6]:
ms_polarity = prepare_sentiment_data_2('Morgan Stanley')
ms_polarity

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

            Morgan Stanley_polarity
date
2015-08-19                   0.9980
2016-07-26                   0.9970
2017-05-12                   0.9900
2017-10-27                   0.9970
2017-11-30                   0.9950
...                             ...
2024-05-03                   0.0575
2024-05-04                   1.0000
2024-05-06                   0.9250
2024-05-07                   0.9270
2024-05-08                   0.3450

[1002 rows x 1 columns]

In [7]:
ct_polarity = prepare_sentiment_data_2('Citigroup')
ct_polarity

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

            Citigroup_polarity
date
2016-02-10           -0.700000
2016-05-09            0.968000
2017-01-09            0.689000
2017-01-17            0.995000
2017-04-05            0.996000
...                        ...
2024-05-03            0.158500
2024-05-04            0.989333
2024-05-06            0.760600
2024-05-07            0.594000
2024-05-08            0.863200

[1076 rows x 1 columns]

In [8]:
sc_polarity = prepare_sentiment_data_2('Standard Chartered')
sc_polarity

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

            Standard Chartered_polarity
date
2020-12-10                     0.980000
2020-12-11                     0.825000
2020-12-21                     0.202000
2020-12-23                     0.995000
2021-01-06                     0.918000
...                                 ...
2024-04-19                     0.981000
2024-04-24                     0.991000
2024-04-26                     0.998000
2024-05-02                     0.802857
2024-05-03                     0.880000

[295 rows x 1 columns]

In [9]:
gs_polarity = prepare_sentiment_data_2('Goldman Sachs')
gs_polarity

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

            Goldman Sachs_polarity
date
2016-04-15                  0.9950
2016-09-13                  0.9960
2016-10-04                  0.9970
2016-10-19                  0.9910
2016-10-26                  0.9960
...                            ...
2024-05-04                  0.9990
2024-05-05                  1.0000
2024-05-06                  0.6258
2024-05-07                  0.8220
2024-05-08                  0.9920

[1161 rows x 1 columns]

In [10]:
cs_polarity = prepare_sentiment_data_2('Credit Suisse')
cs_polarity

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

            Credit Suisse_polarity
date
2017-12-22               -0.903000
2017-12-23                0.072000
2017-12-26                0.850500
2017-12-28                0.851000
2017-12-29                0.432000
...                            ...
2023-06-12                0.671714
2023-06-13                0.152833
2023-06-14                0.452667
2023-06-24                0.999000
2023-06-26                0.998000

[583 rows x 1 columns]

In [11]:
jpm_polarity = prepare_sentiment_data_2('JPMorgan')
jpm_polarity

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

            JPMorgan_polarity
date
2016-02-29           0.998000
2016-03-10           0.999000
2016-03-22           0.998000
2016-04-21           0.998000
2016-04-28           0.881000
...                       ...
2024-05-03           0.934500
2024-05-04           0.999500
2024-05-06           0.906200
2024-05-07           0.336444
2024-05-08           0.445600

[1214 rows x 1 columns]

In [12]:
apple_polarity = prepare_sentiment_data('Apple')
apple_polarity

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

            Apple_polarity
date
2016-02-19        0.994000
2017-10-05        0.997000
2017-11-27        0.997000
2017-11-30        0.989000
2018-01-31        0.995000
...                    ...
2024-05-04        0.903100
2024-05-05        0.764286
2024-05-06        0.718313
2024-05-07        0.556114
2024-05-08        0.606182

[1373 rows x 1 columns]

In [13]:
msft_polarity = prepare_sentiment_data('Microsoft')
msft_polarity

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

            Microsoft_polarity
date
2016-03-07            0.993000
2016-03-08            0.992000
2016-03-16            0.999000
2016-03-24            0.987000
2016-03-29            0.998000
...                        ...
2024-05-04            0.698500
2024-05-05            0.989500
2024-05-06            0.724433
2024-05-07            0.708462
2024-05-08            0.846846

[1328 rows x 1 columns]

In [14]:
nw_polarity = prepare_sentiment_data_2('NatWest')
nw_polarity

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

            NatWest_polarity
date
2020-07-30            0.9920
2020-08-13           -0.9980
2020-11-06            0.9740
2021-01-26           -0.6370
2021-02-05           -0.5820
...                      ...
2024-04-24            0.9825
2024-04-26            0.5270
2024-05-01            0.9845
2024-05-02            0.9700
2024-05-03            1.0000

[336 rows x 1 columns]

In [15]:
polarity_data = pd.merge(apple_polarity,ubs_polarity,left_index=True,right_index=True,how='left')
polarity_data = pd.merge(polarity_data,ms_polarity,left_index=True,right_index=True,how='left')
polarity_data = pd.merge(polarity_data,ct_polarity,left_index=True,right_index=True,how='left')
polarity_data = pd.merge(polarity_data,sc_polarity,left_index=True,right_index=True,how='left')
polarity_data = pd.merge(polarity_data,gs_polarity,left_index=True,right_index=True,how='left')
polarity_data = pd.merge(polarity_data,cs_polarity,left_index=True,right_index=True,how='left')
polarity_data = pd.merge(polarity_data,jpm_polarity,left_index=True,right_index=True,how='left')
polarity_data = pd.merge(polarity_data,nw_polarity,left_index=True,right_index=True,how='left')
polarity_data = pd.merge(polarity_data,hsbc_polarity,left_index=True,right_index=True,how='left')
polarity_data = pd.merge(polarity_data,msft_polarity,left_index=True,right_index=True,how='left')
polarity_data.fillna(0,inplace=True)
polarity_data

,Apple_polarity,UBS_polarity,Morgan Stanley_polarity,Citigroup_polarity,Standard Chartered_polarity,Goldman Sachs_polarity,Credit Suisse_polarity,JPMorgan_polarity,NatWest_polarity,HSBC_polarity,Microsoft_polarity
date,,,,,,,,,,,
2016-02-19,0.994000,0.000000,0.000,0.000000,0.0,0.0000,0.000,0.000000,0.0,0.0000,0.000000
2017-10-05,0.997000,0.000000,0.000,0.000000,0.0,0.0000,0.000,0.000000,0.0,0.0000,0.997000
2017-11-27,0.997000,0.000000,0.000,0.000000,0.0,0.0000,0.000,0.000000,0.0,0.0000,0.000000
2017-11-30,0.989000,0.000000,0.995,0.998000,0.0,0.0000,0.000,0.000000,0.0,0.0000,0.000000
2018-01-31,0.995000,0.000000,0.000,0.000000,0.0,0.0000,-0.875,0.000000,0.0,0.0000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
2024-05-04,0.903100,0.000000,1.000,0.989333,0.0,0.9990,0.000,0.999500,0.0,0.1495,0.698500
2024-05-05,0.764286,0.000000,0.000,0.000000,0.0,1.0000,0.000,0.000000,0.0,0.0000,0.989500
2024-05-06,0.718313,0.841000,0.925,0.760600,0.0,0.6258,0.000,0.906200,0.0,0.9980,0.724433
2024-05-07,0.556114,0.580500,0.927,0.594000,0.0,0.8220,0.000,0.336444,0.0,0.0000,0.708462
2024-05-08,0.606182,0.424333,0.345,0.863200,0.0,0.9920,0.000,0.445600,0.0,0.9980,0.846846

In [16]:
# import toyota stock price
import yfinance as yf

start_date = "2015-05-01"
end_date = "2024-05-08"

stock_data = yf.Ticker('0005.HK')
stock_data = stock_data.history(start=start_date, end=end_date)
stock_data.index = pd.to_datetime(stock_data.index)
stock_data['date'] = stock_data.index
stock_data.reset_index(drop=True, inplace=True)
stock_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits,date
0,40.945867,40.999460,40.383128,40.517113,30752542,0.0,0.0,2015-05-04 00:00:00+08:00
1,40.704704,40.838689,40.034778,40.115170,25859252,0.0,0.0,2015-05-05 00:00:00+08:00
2,39.739996,40.383123,39.686403,39.900776,33206893,0.0,0.0,2015-05-06 00:00:00+08:00
3,39.954367,40.490308,39.847177,40.061554,25310481,0.0,0.0,2015-05-07 00:00:00+08:00
4,40.383122,41.267424,40.222342,41.026253,37785690,0.0,0.0,2015-05-08 00:00:00+08:00
...,...,...,...,...,...,...,...,...
2217,56.571532,57.998797,56.398526,57.955544,39704597,0.0,0.0,2024-04-30 00:00:00+08:00
2218,58.820542,59.901802,58.777289,59.901802,43579704,0.0,0.0,2024-05-02 00:00:00+08:00
2219,60.031553,60.074800,59.728802,59.988300,19885139,0.0,0.0,2024-05-03 00:00:00+08:00
2220,59.988300,60.074799,59.512549,59.858547,22339805,0.0,0.0,2024-05-06 00:00:00+08:00
2221,60.031552,60.420802,59.728800,60.291050,28297946,0.0,0.0,2024-05-07 00:00:00+08:00

In [17]:
stock_data.set_index('date',inplace=True)
stock_data.index = stock_data.index.date

In [18]:
stock_data = pd.merge(stock_data, polarity_data,left_index=True,right_index=True,how='left').fillna(0)
stock_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits,Apple_polarity,UBS_polarity,Morgan Stanley_polarity,Citigroup_polarity,Standard Chartered_polarity,Goldman Sachs_polarity,Credit Suisse_polarity,JPMorgan_polarity,NatWest_polarity,HSBC_polarity,Microsoft_polarity
2015-05-04,40.945867,40.999460,40.383128,40.517113,30752542,0.0,0.0,0.000000,0.0000,0.0000,0.000000,0.000000,0.00000,0.0,0.000000,0.00,0.0000,0.000000
2015-05-05,40.704704,40.838689,40.034778,40.115170,25859252,0.0,0.0,0.000000,0.0000,0.0000,0.000000,0.000000,0.00000,0.0,0.000000,0.00,0.0000,0.000000
2015-05-06,39.739996,40.383123,39.686403,39.900776,33206893,0.0,0.0,0.000000,0.0000,0.0000,0.000000,0.000000,0.00000,0.0,0.000000,0.00,0.0000,0.000000
2015-05-07,39.954367,40.490308,39.847177,40.061554,25310481,0.0,0.0,0.000000,0.0000,0.0000,0.000000,0.000000,0.00000,0.0,0.000000,0.00,0.0000,0.000000
2015-05-08,40.383122,41.267424,40.222342,41.026253,37785690,0.0,0.0,0.000000,0.0000,0.0000,0.000000,0.000000,0.00000,0.0,0.000000,0.00,0.0000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-04-30,56.571532,57.998797,56.398526,57.955544,39704597,0.0,0.0,0.616087,0.0000,0.9960,0.539333,0.000000,0.71450,0.0,0.803429,0.00,0.9666,0.676182
2024-05-02,58.820542,59.901802,58.777289,59.901802,43579704,0.0,0.0,0.687296,0.9990,0.9930,0.974000,0.802857,0.89425,0.0,0.644538,0.97,0.9700,0.833696
2024-05-03,60.031553,60.074800,59.728802,59.988300,19885139,0.0,0.0,0.520036,0.9952,0.0575,0.158500,0.880000,0.86400,0.0,0.934500,1.00,0.9865,0.777059
2024-05-06,59.988300,60.074799,59.512549,59.858547,22339805,0.0,0.0,0.718313,0.8410,0.9250,0.760600,0.000000,0.62580,0.0,0.906200,0.00,0.9980,0.724433
2024-05-07,60.031552,60.420802,59.728800,60.291050,28297946,0.0,0.0,0.556114,0.5805,0.9270,0.594000,0.000000,0.82200,0.0,0.336444,0.00,0.0000,0.708462

# Enhancement Transformer

In [19]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import matplotlib.pyplot as plt
import seaborn as sns
import math
from torch.utils.data import DataLoader, Dataset, random_split
from sklearn.model_selection import train_test_split

In [20]:
import torch.optim as optim
import torch.utils.data as data
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from torch.nn.utils.parametrizations import weight_norm

In [32]:
class MultiHeadAttention(nn.Module):
    def __init__(self, d_model, n_heads, dropout=0.1):
        super(MultiHeadAttention, self).__init__()
        self.attention = nn.MultiheadAttention(
            embed_dim=d_model,
            num_heads=n_heads,
            dropout=dropout,
            batch_first=True  # accepts (batch, seq_len, features)
        )

    def forward(self, x):
        # x shape: (batch, seq_len, features)
        attn_output, attn_weights = self.attention(x, x, x)
        return attn_output, attn_weights

class TransformerEncoderLayer(nn.Module):
    def __init__(self, d_model, n_heads, dropout=0.1):
        super(TransformerEncoderLayer, self).__init__()
        self.mha = MultiHeadAttention(d_model, n_heads, dropout)

        self.ffn = nn.Sequential(
            nn.Linear(d_model, d_model * 4),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(d_model * 4, d_model),
            nn.Dropout(dropout)
        )

        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.dropout1 = nn.Dropout(dropout)
        self.dropout2 = nn.Dropout(dropout)

    def forward(self, x):
        # x: (batch, seq_len, features)
        attn_output, attn_weights = self.mha(x)
        x = self.norm1(x + self.dropout1(attn_output))
        ffn_output = self.ffn(x)
        x = self.norm2(x + self.dropout2(ffn_output))
        return x, attn_weights

class Trans(nn.Module):
    def __init__(self, input_size, trans_hidden_size, seq_len, trans_n_heads, trans_n_layers):
        super(Trans, self).__init__()
        self.input_size = input_size
        self.trans_hidden_size = trans_hidden_size
        self.seq_len = seq_len

        # Project input_size -> trans_hidden_size
        self.feature_proj = nn.Linear(input_size, trans_hidden_size)

        # Project back to input_size
        self.output_proj = nn.Linear(trans_hidden_size, input_size)

        # Positional encoding: (1, seq_len, hidden) for batch_first
        self.pos_encoding = nn.Parameter(torch.randn(1, seq_len, trans_hidden_size) * 0.1)

        # Transformer layers
        self.transformer_layers = nn.ModuleList(
            [TransformerEncoderLayer(trans_hidden_size, trans_n_heads) for _ in range(trans_n_layers)]
        )

    def forward(self, x):
        # x: (batch_size, seq_len, input_size) - matches dataloader!
        batch_size, seq_len, input_size = x.shape

        # Project features
        x = self.feature_proj(x)  # (batch, seq_len, hidden)

        # Add positional encoding
        x = x + self.pos_encoding

        # Pass through transformer layers
        attn_weights_list = []
        for layer in self.transformer_layers:
            x, attn_weights = layer(x)
            attn_weights_list.append(attn_weights)

        # Project back
        x = self.output_proj(x)  # (batch, seq_len, input_size)

        return x, attn_weights_list

In [36]:
class PolarityDataset(Dataset):
    def __init__(self, data, time_steps=5):
        # Convert to numpy array if it's a DataFrame
        if hasattr(data, 'values'):
            self.data = data.values  # DataFrame → NumPy array
        else:
            self.data = data
        self.time_steps = time_steps

    def __len__(self):
        return len(self.data) - self.time_steps + 1

    def __getitem__(self, idx):
        window = self.data[idx : idx + self.time_steps]  # Now it's a NumPy array
        return torch.tensor(window, dtype=torch.float32)

In [37]:
def train_model_autoencoder(model, train_loader, test_loader, criterion, optimizer, num_epochs, device):
    """
    Train autoencoder with batch_first=True
    Model expects: (batch_size, seq_len, num_features)
    DataLoader gives: (batch_size, seq_len, num_features)

    """
    model.to(device)
    train_losses = []
    test_losses = []

    for epoch in range(num_epochs):
        # Training phase
        model.train()
        epoch_train_loss = 0
        for inputs in train_loader:
            # inputs: (batch_size, seq_len, num_features)
            inputs = inputs.to(device)

            # Forward pass - model accepts (batch, seq_len, features)
            outputs, _ = model(inputs)  # outputs: (batch, seq_len, features)

            # Loss calculation - same shape
            loss = criterion(outputs, inputs)

            # Backward pass
            optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
            optimizer.step()

            epoch_train_loss += loss.item()

        # Evaluation phase
        model.eval()
        epoch_test_loss = 0
        with torch.no_grad():
            for inputs in test_loader:
                inputs = inputs.to(device)
                outputs, _ = model(inputs)
                loss = criterion(outputs, inputs)
                epoch_test_loss += loss.item()

        avg_train_loss = epoch_train_loss / len(train_loader)
        avg_test_loss = epoch_test_loss / len(test_loader)
        train_losses.append(avg_train_loss)
        test_losses.append(avg_test_loss)

        print(
            f"Epoch [{epoch + 1}/{num_epochs}], "
            f"Train Loss: {avg_train_loss:.6f}, "
            f"Test Loss: {avg_test_loss:.6f}"
        )

    return train_losses, test_losses

In [41]:
# Hyperparameters
input_size = len(polarity_data.columns.to_list())  # Number of companies (features)
trans_hidden_size = 32
seq_len = 5
trans_n_heads = 4
trans_n_layers = 2
batch_size = 16
num_epochs = 50
learning_rate = 0.001

# Load dataset
df = stock_data[polarity_data.columns.to_list()]
split_index = int(len(stock_data) * 0.7)
train_data = df.iloc[:split_index]  # First 70% as training
test_data = df.iloc[split_index:]  # Last 30% as testing

# Create datasets - each sample is (seq_len, num_features)
train_dataset = PolarityDataset(train_data, time_steps=seq_len)
test_dataset = PolarityDataset(test_data, time_steps=seq_len)

# Create DataLoaders
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

# Define model
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = Trans(input_size, trans_hidden_size, seq_len, trans_n_heads, trans_n_layers)

# Loss and optimizer
criterion = nn.MSELoss()  # Reconstruction loss
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# Train
train_losses, test_losses = train_model_autoencoder(
    model, train_loader, test_loader,
    criterion, optimizer, num_epochs, device
)

Epoch [1/50], Train Loss: 0.051445, Test Loss: 0.161835
Epoch [2/50], Train Loss: 0.037504, Test Loss: 0.105447
Epoch [3/50], Train Loss: 0.016618, Test Loss: 0.058778
Epoch [4/50], Train Loss: 0.008834, Test Loss: 0.032748
Epoch [5/50], Train Loss: 0.005874, Test Loss: 0.023853
Epoch [6/50], Train Loss: 0.004580, Test Loss: 0.018719
Epoch [7/50], Train Loss: 0.003299, Test Loss: 0.014013
Epoch [8/50], Train Loss: 0.002815, Test Loss: 0.011918
Epoch [9/50], Train Loss: 0.002602, Test Loss: 0.013278
Epoch [10/50], Train Loss: 0.002279, Test Loss: 0.017067
Epoch [11/50], Train Loss: 0.002120, Test Loss: 0.010858
Epoch [12/50], Train Loss: 0.002001, Test Loss: 0.011806
Epoch [13/50], Train Loss: 0.001760, Test Loss: 0.010798
Epoch [14/50], Train Loss: 0.001283, Test Loss: 0.008361
Epoch [15/50], Train Loss: 0.001032, Test Loss: 0.007171
Epoch [16/50], Train Loss: 0.000925, Test Loss: 0.006308
Epoch [17/50], Train Loss: 0.000889, Test Loss: 0.006000
Epoch [18/50], Train Loss: 0.000757, Test Loss: 0.004179
Epoch [19/50], Train Loss: 0.000672, Test Loss: 0.004000
Epoch [20/50], Train Loss: 0.000676, Test Loss: 0.004435
Epoch [21/50], Train Loss: 0.000648, Test Loss: 0.003786
Epoch [22/50], Train Loss: 0.000588, Test Loss: 0.003896
Epoch [23/50], Train Loss: 0.000701, Test Loss: 0.004589
Epoch [24/50], Train Loss: 0.000737, Test Loss: 0.004185
Epoch [25/50], Train Loss: 0.000791, Test Loss: 0.005621
Epoch [26/50], Train Loss: 0.000993, Test Loss: 0.010014
Epoch [27/50], Train Loss: 0.000986, Test Loss: 0.009169
Epoch [28/50], Train Loss: 0.000894, Test Loss: 0.008778
Epoch [29/50], Train Loss: 0.000699, Test Loss: 0.004425
Epoch [30/50], Train Loss: 0.000576, Test Loss: 0.003506
Epoch [31/50], Train Loss: 0.000643, Test Loss: 0.004052
Epoch [32/50], Train Loss: 0.000632, Test Loss: 0.005493
Epoch [33/50], Train Loss: 0.000694, Test Loss: 0.005280
Epoch [34/50], Train Loss: 0.000733, Test Loss: 0.005096
Epoch [35/50], Train Loss: 0.000607, Test Loss: 0.005090
Epoch [36/50], Train Loss: 0.000464, Test Loss: 0.003324
Epoch [37/50], Train Loss: 0.000404, Test Loss: 0.002423
Epoch [38/50], Train Loss: 0.000352, Test Loss: 0.002716
Epoch [39/50], Train Loss: 0.000327, Test Loss: 0.002613
Epoch [40/50], Train Loss: 0.000355, Test Loss: 0.002695
Epoch [41/50], Train Loss: 0.000350, Test Loss: 0.002467
Epoch [42/50], Train Loss: 0.000359, Test Loss: 0.002944
Epoch [43/50], Train Loss: 0.000404, Test Loss: 0.003073
Epoch [44/50], Train Loss: 0.000411, Test Loss: 0.002288
Epoch [45/50], Train Loss: 0.000428, Test Loss: 0.003763
Epoch [46/50], Train Loss: 0.000429, Test Loss: 0.002134
Epoch [47/50], Train Loss: 0.000401, Test Loss: 0.003658
Epoch [48/50], Train Loss: 0.000430, Test Loss: 0.002092
Epoch [49/50], Train Loss: 0.000396, Test Loss: 0.002967
Epoch [50/50], Train Loss: 0.000408, Test Loss: 0.002079

In [42]:
def generate_sentiment_features(model, dataloader, device):
    model.eval()  # Set the model to evaluation mode

    all_outputs = []
    all_inputs = []
    all_attn_weights = []

    with torch.no_grad():
        for inputs in dataloader:
            inputs = inputs.to(device)
            outputs, attn_weights = model(inputs)  # Get the output features

            all_outputs.append(outputs.cpu())  # Collect outputs
            all_inputs.append(inputs.cpu())  # Collect inputs
            all_attn_weights.append(attn_weights)  # Collect attention weights

    # Concatenate all batches along batch dimension
    all_outputs = torch.cat(all_outputs, dim=0)  # Shape: (total_samples, seq_len, num_features)
    all_inputs = torch.cat(all_inputs, dim=0)  # Shape: (total_samples, seq_len, num_features)

    # Attention weights may be a list (one per layer), so handle accordingly
    all_attn_weights = [torch.cat(attn, dim=0) for attn in zip(*all_attn_weights)]

    return all_outputs.numpy(), all_inputs.numpy(), all_attn_weights

In [43]:
# Generate sentiment features using the trained model on the training set
sentiment_features_train, sentiment_inputs_train, attn_weights = generate_sentiment_features(
    model, train_loader, device
)

In [44]:
# Generate sentiment features using the trained model on the testing set
sentiment_features_test, sentiment_inputs_test, attn_weights_test = generate_sentiment_features(
    model, test_loader, device
)

In [45]:
close_train = []
train_target = []

for i in range(len(sentiment_features_train - 5)):
    close_train.append(stock_data['Close'].iloc[i:i+5])
    train_target.append(stock_data['Close'].iloc[i+5])

In [46]:
train_close = np.array(close_train)
train_close.shape

(1551, 5)

In [47]:
new_train_data = np.concatenate((sentiment_features_train,np.expand_dims(train_close,axis=-1)),axis=-1)
new_train_data.shape

(1551, 5, 12)

In [48]:
close_test = []
test_target = []

for i in range(len(sentiment_features_test - 5)):
    close_test.append(stock_data['Close'].iloc[i:i+5])
    test_target.append(stock_data['Close'].iloc[i+5])

In [49]:
test_close = np.array(close_test)
test_close.shape

(663, 5)

In [50]:
new_test_data = np.concatenate((sentiment_features_test,np.expand_dims(test_close,axis=-1)),axis=-1)
new_test_data.shape

(663, 5, 12)

In [51]:
sentiment_features_train = pd.DataFrame(np.mean(sentiment_features_train,axis=1),columns=polarity_data.columns.to_list())

sentiment_features_train.index = stock_data[['Close']].iloc[:len(sentiment_features_train)].index

stock_data_train = pd.concat([stock_data[['Close']].iloc[:len(sentiment_features_train)],sentiment_features_train],axis=1)
stock_data_train

,Close,Apple_polarity,UBS_polarity,Morgan Stanley_polarity,Citigroup_polarity,Standard Chartered_polarity,Goldman Sachs_polarity,Credit Suisse_polarity,JPMorgan_polarity,NatWest_polarity,HSBC_polarity,Microsoft_polarity
2015-05-04,40.517113,-0.025228,0.022214,0.040256,-0.002197,0.028371,-0.049310,0.002933,-0.020793,-0.021611,-0.000171,-0.049564
2015-05-05,40.115170,-0.025228,0.022214,0.040256,-0.002197,0.028371,-0.049310,0.002933,-0.020793,-0.021611,-0.000171,-0.049564
2015-05-06,39.900776,-0.025228,0.022214,0.040256,-0.002197,0.028371,-0.049310,0.002933,-0.020793,-0.021611,-0.000171,-0.049564
2015-05-07,40.061554,-0.025228,0.022214,0.040256,-0.002197,0.028371,-0.049310,0.002933,-0.020793,-0.021611,-0.000171,-0.049564
2015-05-08,41.026253,-0.025228,0.022214,0.040256,-0.002197,0.028371,-0.049310,0.002933,-0.020793,-0.021611,-0.000171,-0.049564
...,...,...,...,...,...,...,...,...,...,...,...,...
2021-08-05,31.730761,0.411811,0.389014,0.795391,0.594431,0.066991,0.747660,-0.186374,0.802823,0.355031,0.055288,0.566410
2021-08-06,31.657467,0.445417,0.385906,0.660085,0.853251,0.066709,0.726961,-0.045136,0.749199,0.365171,0.260565,0.655004
2021-08-09,32.097157,0.443443,0.184768,0.624453,0.859141,0.072246,0.739293,-0.394685,0.851343,0.164685,0.251510,0.554572
2021-08-10,32.097157,0.444694,0.167875,0.606669,0.852604,0.262156,0.746495,-0.388703,0.716621,-0.022984,0.441443,0.559450
2021-08-11,32.280354,0.463409,0.169007,0.490651,0.925204,0.183561,0.598226,-0.201058,0.730018,-0.018105,0.400196,0.489470

In [52]:
sentiment_features_test = pd.DataFrame(np.mean(sentiment_features_test,axis=1),columns=polarity_data.columns.to_list())
sentiment_features_test.index = stock_data[['Close']].iloc[len(sentiment_features_train):len(sentiment_features_train)+len(sentiment_features_test)].index

stock_data_test = pd.concat([stock_data[['Close']].iloc[len(sentiment_features_train):len(sentiment_features_train)+len(sentiment_features_test)],sentiment_features_test],axis=1)
stock_data_test

,Close,Apple_polarity,UBS_polarity,Morgan Stanley_polarity,Citigroup_polarity,Standard Chartered_polarity,Goldman Sachs_polarity,Credit Suisse_polarity,JPMorgan_polarity,NatWest_polarity,HSBC_polarity,Microsoft_polarity
2021-08-12,32.463562,0.371515,0.371872,0.838155,0.291625,-0.081336,0.251543,-0.011304,0.926926,0.041983,0.023016,0.707490
2021-08-13,32.390274,0.457146,0.451154,0.654712,0.346277,-0.086850,0.146796,0.125195,0.821025,-0.149901,-0.198574,0.665492
2021-08-16,32.500198,0.569799,0.492009,0.674788,0.333181,-0.087294,0.270777,0.123655,0.619604,-0.153897,-0.008305,0.609751
2021-08-17,32.133793,0.573656,0.503856,0.638923,0.682800,0.040558,0.385277,0.158344,0.609563,-0.359863,-0.169264,0.616624
2021-08-18,31.804028,0.580748,0.502628,0.830661,0.746726,0.030631,0.504376,0.147622,0.616848,-0.446906,-0.173644,0.589512
...,...,...,...,...,...,...,...,...,...,...,...,...
2024-04-18,54.192749,0.492346,0.224069,0.796241,0.630125,0.393498,0.797604,-0.015650,0.863468,0.280754,0.766742,0.602954
2024-04-19,53.500744,0.486751,0.530618,0.813292,0.686707,0.359496,0.861418,-0.013849,0.858985,0.271648,0.777418,0.606878
2024-04-22,54.841507,0.585227,0.718998,0.725457,0.514887,0.521895,0.831555,-0.014549,0.836226,0.472904,0.968372,0.611887
2024-04-23,55.576759,0.628130,0.703079,0.747069,0.485067,0.340869,0.771587,-0.019372,0.819585,0.375914,1.006651,0.639630
2024-04-24,55.966011,0.576469,0.692107,0.841406,0.611420,0.341626,0.741914,-0.011276,0.728250,0.363737,0.813767,0.681631

In [53]:
X = ['Close',
     'Apple_polarity',
     'UBS_polarity',
     'Morgan Stanley_polarity',
      'Citigroup_polarity',
     'Standard Chartered_polarity',
      'Goldman Sachs_polarity',
     'Credit Suisse_polarity',
     'JPMorgan_polarity',
      'NatWest_polarity',
     'HSBC_polarity',
     'Microsoft_polarity']

In [54]:
stock_data_train = stock_data_train[X]
stock_data_test = stock_data_test[X]

In [55]:
stock_data = pd.concat([stock_data_train,stock_data_test])
stock_data['date'] = stock_data.index
stock_data

,Close,Apple_polarity,UBS_polarity,Morgan Stanley_polarity,Citigroup_polarity,Standard Chartered_polarity,Goldman Sachs_polarity,Credit Suisse_polarity,JPMorgan_polarity,NatWest_polarity,HSBC_polarity,Microsoft_polarity,date
2015-05-04,40.517113,-0.025228,0.022214,0.040256,-0.002197,0.028371,-0.049310,0.002933,-0.020793,-0.021611,-0.000171,-0.049564,2015-05-04
2015-05-05,40.115170,-0.025228,0.022214,0.040256,-0.002197,0.028371,-0.049310,0.002933,-0.020793,-0.021611,-0.000171,-0.049564,2015-05-05
2015-05-06,39.900776,-0.025228,0.022214,0.040256,-0.002197,0.028371,-0.049310,0.002933,-0.020793,-0.021611,-0.000171,-0.049564,2015-05-06
2015-05-07,40.061554,-0.025228,0.022214,0.040256,-0.002197,0.028371,-0.049310,0.002933,-0.020793,-0.021611,-0.000171,-0.049564,2015-05-07
2015-05-08,41.026253,-0.025228,0.022214,0.040256,-0.002197,0.028371,-0.049310,0.002933,-0.020793,-0.021611,-0.000171,-0.049564,2015-05-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-04-18,54.192749,0.492346,0.224069,0.796241,0.630125,0.393498,0.797604,-0.015650,0.863468,0.280754,0.766742,0.602954,2024-04-18
2024-04-19,53.500744,0.486751,0.530618,0.813292,0.686707,0.359496,0.861418,-0.013849,0.858985,0.271648,0.777418,0.606878,2024-04-19
2024-04-22,54.841507,0.585227,0.718998,0.725457,0.514887,0.521895,0.831555,-0.014549,0.836226,0.472904,0.968372,0.611887,2024-04-22
2024-04-23,55.576759,0.628130,0.703079,0.747069,0.485067,0.340869,0.771587,-0.019372,0.819585,0.375914,1.006651,0.639630,2024-04-23
2024-04-24,55.966011,0.576469,0.692107,0.841406,0.611420,0.341626,0.741914,-0.011276,0.728250,0.363737,0.813767,0.681631,2024-04-24

# Forecast Transformer

In [56]:
def compared_version(ver1, ver2):
    """
    :param ver1
    :param ver2
    :return: ver1< = >ver2 False/True
    """
    list1 = str(ver1).split(".")
    list2 = str(ver2).split(".")

    for i in range(len(list1)) if len(list1) < len(list2) else range(len(list2)):
        if int(list1[i]) == int(list2[i]):
            pass
        elif int(list1[i]) < int(list2[i]):
            return -1
        else:
            return 1

    if len(list1) == len(list2):
        return True
    elif len(list1) < len(list2):
        return False
    else:
        return True


class PositionalEmbedding(nn.Module):
    def __init__(self, d_model, max_len=5000):
        super(PositionalEmbedding, self).__init__()
        # Compute the positional encodings once in log space.
        pe = torch.zeros(max_len, d_model).float()
        pe.require_grad = False

        position = torch.arange(0, max_len).float().unsqueeze(1)
        div_term = (torch.arange(0, d_model, 2).float() * -(math.log(10000.0) / d_model)).exp()

        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)

        pe = pe.unsqueeze(0)
        self.register_buffer('pe', pe)

    def forward(self, x):
        return self.pe[:, :x.size(1)]


class TokenEmbedding(nn.Module):
    def __init__(self, c_in, d_model):
        super(TokenEmbedding, self).__init__()
        padding = 1 if compared_version(torch.__version__, '1.5.0') else 2
        self.tokenConv = nn.Conv1d(in_channels=c_in, out_channels=d_model,
                                   kernel_size=3, padding=padding, padding_mode='circular', bias=False)
        for m in self.modules():
            if isinstance(m, nn.Conv1d):
                nn.init.kaiming_normal_(m.weight, mode='fan_in', nonlinearity='leaky_relu')

    def forward(self, x):
        x = self.tokenConv(x.permute(0, 2, 1)).transpose(1, 2)
        return x


class FixedEmbedding(nn.Module):
    def __init__(self, c_in, d_model):
        super(FixedEmbedding, self).__init__()

        w = torch.zeros(c_in, d_model).float()
        w.require_grad = False

        position = torch.arange(0, c_in).float().unsqueeze(1)
        div_term = (torch.arange(0, d_model, 2).float() * -(math.log(10000.0) / d_model)).exp()

        w[:, 0::2] = torch.sin(position * div_term)
        w[:, 1::2] = torch.cos(position * div_term)

        self.emb = nn.Embedding(c_in, d_model)
        self.emb.weight = nn.Parameter(w, requires_grad=False)

    def forward(self, x):
        return self.emb(x).detach()


class TemporalEmbedding(nn.Module):
    def __init__(self, d_model, embed_type='fixed', freq='h'):
        super(TemporalEmbedding, self).__init__()

        weekday_size = 365
        day_size = 365
        month_size = 365

        Embed = FixedEmbedding if embed_type == 'fixed' else nn.Embedding

        self.weekday_embed = Embed(weekday_size, d_model)
        self.day_embed = Embed(day_size, d_model)
        self.month_embed = Embed(month_size, d_model)

    def forward(self, x):
        x = x.long()

        weekday_x = self.weekday_embed(x[:, :, 2])
        day_x = self.day_embed(x[:, :, 1])
        month_x = self.month_embed(x[:, :, 0])

        return weekday_x + day_x + month_x


class TimeFeatureEmbedding(nn.Module):
    def __init__(self, d_model, embed_type='timeF', freq='h'):
        super(TimeFeatureEmbedding, self).__init__()

        freq_map = {'h': 4, 't': 5, 's': 6, 'm': 1, 'a': 1, 'w': 2, 'd': 3, 'b': 3}
        d_inp = freq_map[freq]
        self.embed = nn.Linear(d_inp, d_model, bias=False)

    def forward(self, x):
        return self.embed(x)


class DataEmbedding(nn.Module):
    def __init__(self, c_in, d_model, embed_type='fixed', freq='h', dropout=0.1):
        super(DataEmbedding, self).__init__()

        self.value_embedding = TokenEmbedding(c_in=c_in, d_model=d_model)
        self.position_embedding = PositionalEmbedding(d_model=d_model)
        self.temporal_embedding = TemporalEmbedding(d_model=d_model, embed_type=embed_type,
                                                    freq=freq) if embed_type != 'timeF' else TimeFeatureEmbedding(
            d_model=d_model, embed_type=embed_type, freq=freq)
        self.dropout = nn.Dropout(p=dropout)

    def forward(self, x, x_mark):
        x = self.value_embedding(x) + self.temporal_embedding(x_mark) + self.position_embedding(x)
        return self.dropout(x)

In [57]:
from math import sqrt


class TriangularCausalMask():
    def __init__(self, B, L, device="cpu"):
        mask_shape = [B, 1, L, L]
        with torch.no_grad():
            self._mask = torch.triu(torch.ones(mask_shape, dtype=torch.bool), diagonal=1).to(device)

    @property
    def mask(self):
        return self._mask


class ProbMask():
    def __init__(self, B, H, L, index, scores, device="cpu"):
        _mask = torch.ones(L, scores.shape[-1], dtype=torch.bool).to(device).triu(1)
        _mask_ex = _mask[None, None, :].expand(B, H, L, scores.shape[-1])
        indicator = _mask_ex[torch.arange(B)[:, None, None],
                    torch.arange(H)[None, :, None],
                    index, :].to(device)
        self._mask = indicator.view(scores.shape).to(device)

    @property
    def mask(self):
        return self._mask


class FullAttention(nn.Module):
    def __init__(self, mask_flag=True, factor=5, scale=None, attention_dropout=0.1, output_attention=False):
        super(FullAttention, self).__init__()
        self.scale = scale
        self.mask_flag = mask_flag
        self.output_attention = output_attention
        self.dropout = nn.Dropout(attention_dropout)

    def forward(self, queries, keys, values, attn_mask):
        B, L, H, E = queries.shape
        _, S, _, D = values.shape
        scale = self.scale or 1. / sqrt(E)

        scores = torch.einsum("blhe,bshe->bhls", queries, keys)

        if self.mask_flag:
            if attn_mask is None:
                attn_mask = TriangularCausalMask(B, L, device=queries.device)

            scores.masked_fill_(attn_mask.mask, -np.inf)

        A = self.dropout(torch.softmax(scale * scores, dim=-1))
        V = torch.einsum("bhls,bshd->blhd", A, values)

        if self.output_attention:
            return (V.contiguous(), A)
        else:
            return (V.contiguous(), None)

class AttentionLayer(nn.Module):
    def __init__(self, attention, d_model, n_heads, d_keys=None,
                 d_values=None):
        super(AttentionLayer, self).__init__()

        d_keys = d_keys or (d_model // n_heads)
        d_values = d_values or (d_model // n_heads)

        self.inner_attention = attention
        self.query_projection = nn.Linear(d_model, d_keys * n_heads)
        self.key_projection = nn.Linear(d_model, d_keys * n_heads)
        self.value_projection = nn.Linear(d_model, d_values * n_heads)
        self.out_projection = nn.Linear(d_values * n_heads, d_model)
        self.n_heads = n_heads

    def forward(self, queries, keys, values, attn_mask):
        B, L, _ = queries.shape
        _, S, _ = keys.shape
        H = self.n_heads

        queries = self.query_projection(queries).view(B, L, H, -1)
        keys = self.key_projection(keys).view(B, S, H, -1)
        values = self.value_projection(values).view(B, S, H, -1)

        out, attn = self.inner_attention(
            queries,
            keys,
            values,
            attn_mask
        )
        out = out.view(B, L, -1)

        return self.out_projection(out), attn

In [58]:
class ConvLayer(nn.Module):
    def __init__(self, c_in):
        super(ConvLayer, self).__init__()
        self.downConv = nn.Conv1d(in_channels=c_in,
                                  out_channels=c_in,
                                  kernel_size=3,
                                  padding=2,
                                  padding_mode='circular')
        self.norm = nn.BatchNorm1d(c_in)
        self.activation = nn.ELU()
        self.maxPool = nn.MaxPool1d(kernel_size=3, stride=2, padding=1)

    def forward(self, x):
        x = self.downConv(x.permute(0, 2, 1))
        x = self.norm(x)
        x = self.activation(x)
        x = self.maxPool(x)
        x = x.transpose(1, 2)
        return x


class EncoderLayer(nn.Module):
    def __init__(self, attention, d_model, d_ff=None, dropout=0.1, activation="relu"):
        super(EncoderLayer, self).__init__()
        d_ff = d_ff or 4 * d_model
        self.attention = attention
        self.conv1 = nn.Conv1d(in_channels=d_model, out_channels=d_ff, kernel_size=1)
        self.conv2 = nn.Conv1d(in_channels=d_ff, out_channels=d_model, kernel_size=1)
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.dropout = nn.Dropout(dropout)
        self.activation = F.relu if activation == "relu" else F.gelu

    def forward(self, x, attn_mask=None):
        new_x, attn = self.attention(
            x, x, x,
            attn_mask=attn_mask
        )
        x = x + self.dropout(new_x)

        y = x = self.norm1(x)
        y = self.dropout(self.activation(self.conv1(y.transpose(-1, 1))))
        y = self.dropout(self.conv2(y).transpose(-1, 1))

        return self.norm2(x + y), attn


class Encoder(nn.Module):
    def __init__(self, attn_layers, conv_layers=None, norm_layer=None):
        super(Encoder, self).__init__()
        self.attn_layers = nn.ModuleList(attn_layers)
        self.conv_layers = nn.ModuleList(conv_layers) if conv_layers is not None else None
        self.norm = norm_layer

    def forward(self, x, attn_mask=None):
        # x [B, L, D]
        attns = []
        if self.conv_layers is not None:
            for attn_layer, conv_layer in zip(self.attn_layers, self.conv_layers):
                x, attn = attn_layer(x, attn_mask=attn_mask)
                x = conv_layer(x)
                attns.append(attn)
            x, attn = self.attn_layers[-1](x)
            attns.append(attn)
        else:
            for attn_layer in self.attn_layers:
                x, attn = attn_layer(x, attn_mask=attn_mask)
                attns.append(attn)

        if self.norm is not None:
            x = self.norm(x)

        return x, attns


class DecoderLayer(nn.Module):
    def __init__(self, self_attention, cross_attention, d_model, d_ff=None,
                 dropout=0.1, activation="relu"):
        super(DecoderLayer, self).__init__()
        d_ff = d_ff or 4 * d_model
        self.self_attention = self_attention
        self.cross_attention = cross_attention
        self.conv1 = nn.Conv1d(in_channels=d_model, out_channels=d_ff, kernel_size=1)
        self.conv2 = nn.Conv1d(in_channels=d_ff, out_channels=d_model, kernel_size=1)
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.norm3 = nn.LayerNorm(d_model)
        self.dropout = nn.Dropout(dropout)
        self.activation = F.relu if activation == "relu" else F.gelu

    def forward(self, x, cross, x_mask=None, cross_mask=None):
        x = x + self.dropout(self.self_attention(
            x, x, x,
            attn_mask=x_mask
        )[0])
        x = self.norm1(x)

        x = x + self.dropout(self.cross_attention(
            x, cross, cross,
            attn_mask=cross_mask
        )[0])

        y = x = self.norm2(x)
        y = self.dropout(self.activation(self.conv1(y.transpose(-1, 1))))
        y = self.dropout(self.conv2(y).transpose(-1, 1))

        return self.norm3(x + y)


class Decoder(nn.Module):
    def __init__(self, layers, norm_layer=None, projection=None):
        super(Decoder, self).__init__()
        self.layers = nn.ModuleList(layers)
        self.norm = norm_layer
        self.projection = projection

    def forward(self, x, cross, x_mask=None, cross_mask=None):
        for layer in self.layers:
            x = layer(x, cross, x_mask=x_mask, cross_mask=cross_mask)

        if self.norm is not None:
            x = self.norm(x)

        if self.projection is not None:
            x = self.projection(x)
        return x

In [59]:
class Model(nn.Module):
    """
    Vanilla Transformer with O(L^2) complexity
    """
    def __init__(self, pred_len=1, output_attention=False, enc_in=len(X), dec_in=1, c_out=1, d_model=512, embed='fixed',
                 freq='h', dropout=0.0, factor=5, n_heads=8, d_ff=512, activation='gelu', e_layers=3, d_layers=2):
        super(Model, self).__init__()
        self.pred_len = pred_len
        self.output_attention = output_attention

        # Embedding
        self.enc_embedding = DataEmbedding(enc_in, d_model, embed, freq,
                                           dropout)
        self.dec_embedding = DataEmbedding(dec_in, d_model, embed, freq,
                                           dropout)
        # Encoder
        self.encoder = Encoder(
            [
                EncoderLayer(
                    AttentionLayer(
                        FullAttention(False, factor, attention_dropout=dropout,
                                      output_attention=output_attention), d_model, n_heads),
                    d_model,
                    d_ff,
                    dropout=dropout,
                    activation=activation
                ) for l in range(e_layers)
            ],
            norm_layer=torch.nn.LayerNorm(d_model)
        )
        # Decoder
        self.decoder = Decoder(
            [
                DecoderLayer(
                    AttentionLayer(
                        FullAttention(True, factor, attention_dropout=dropout, output_attention=False),
                        d_model, n_heads),
                    AttentionLayer(
                        FullAttention(False, factor, attention_dropout=dropout, output_attention=False),
                        d_model, n_heads),
                    d_model,
                    d_ff,
                    dropout=dropout,
                    activation=activation,
                )
                for l in range(d_layers)
            ],
            norm_layer=torch.nn.LayerNorm(d_model),
            projection=nn.Linear(d_model, c_out, bias=True)
        )

    def forward(self, x_enc, x_mark_enc, x_dec, x_mark_dec,
                enc_self_mask=None, dec_self_mask=None, dec_enc_mask=None):

        enc_out = self.enc_embedding(x_enc, x_mark_enc)
        enc_out, attns = self.encoder(enc_out, attn_mask=enc_self_mask)

        dec_out = self.dec_embedding(x_dec, x_mark_dec)
        dec_out = self.decoder(dec_out, enc_out, x_mask=dec_self_mask, cross_mask=dec_enc_mask)

        if self.output_attention:
            return dec_out[:, -self.pred_len:, :], attns
        else:
            return dec_out[:, -self.pred_len:, :]  # [B, L, D]

In [60]:
import numpy as np
import pandas as pd
from tqdm import tqdm

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import MinMaxScaler

# ==========================
# Hyperparameters
# ==========================

train_size = 0.7
s_len = 5
pre_len = 1

batch_size = 64
lr = 5e-5
epochs = 20


# ==========================
# Sliding Window Generation
# ==========================

def create_data(datas, s_len):

    values = []
    labels = []

    lens = datas.shape[0]
    datas = datas.values

    for index in range(lens - s_len - pre_len):

        value = datas[
            index:index+s_len,
            [stock_data.columns.get_loc('date')] +
            [stock_data.columns.get_loc(col) for col in X]
        ]

        label = datas[
            index+s_len-pre_len:index+s_len+pre_len,
            [
                stock_data.columns.get_loc('date'),
                stock_data.columns.get_loc('Close')
            ]
        ]

        values.append(value)
        labels.append(label)

    return values, labels


# ==========================
# Dataset
# ==========================

class AmaData(Dataset):

    def __init__(self, values, labels, x_scaler, y_scaler):

        self.values = values
        self.labels = labels
        self.x_scaler = x_scaler
        self.y_scaler = y_scaler

    def __len__(self):
        return len(self.values)

    def create_time(self, data):

        time = pd.to_datetime(data[:, 0])

        week = np.int32(time.dayofweek)[:, None]
        month = np.int32(time.month)[:, None]
        day = np.int32(time.day)[:, None]

        return np.concatenate([month, week, day], axis=-1)

    def __getitem__(self, idx):

        value = self.values[idx]
        label = self.labels[idx]

        value_t = self.create_time(value)
        label_t = self.create_time(label)

        value = self.x_scaler.transform(value[:, 1:])
        label = self.y_scaler.transform(label[:, 1][:, None])

        value = torch.FloatTensor(value)
        label = torch.FloatTensor(label)

        value_t = torch.LongTensor(value_t)
        label_t = torch.LongTensor(label_t)

        return value, label, value_t, label_t


# ==========================
# Read Data
# ==========================

def read_data(data, s_len):

    values, labels = create_data(data, s_len)

    split_idx = int(len(values) * train_size)

    train_x = values[:split_idx]
    train_y = labels[:split_idx]

    test_x = values[split_idx:]
    test_y = labels[split_idx:]

    x_scaler = MinMaxScaler()
    y_scaler = MinMaxScaler()

    train_features = np.concatenate(
        [x[:, 1:] for x in train_x],
        axis=0
    )

    train_targets = np.concatenate(
        [y[:, 1:] for y in train_y],
        axis=0
    )

    x_scaler.fit(train_features)
    y_scaler.fit(train_targets)

    return (
        train_x,
        test_x,
        train_y,
        test_y,
        x_scaler,
        y_scaler
    )


# ==========================
# Training
# ==========================

def TransformerTrain(data, s_len):

    (
        train_x,
        test_x,
        train_y,
        test_y,
        x_scaler,
        y_scaler
    ) = read_data(data, s_len)

    train_dataset = AmaData(
        train_x,
        train_y,
        x_scaler,
        y_scaler
    )

    test_dataset = AmaData(
        test_x,
        test_y,
        x_scaler,
        y_scaler
    )

    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=batch_size,
        shuffle=False
    )

    model = Model()

    mse_loss = nn.MSELoss()
    mae_loss = nn.L1Loss()

    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=lr
    )

    best_loss = float("inf")
    best_model = None

    for epoch in range(epochs):

        ########################
        # Training
        ########################

        model.train()

        train_mse = 0
        train_mae = 0

        for x, y, xt, yt in tqdm(train_loader):

            mask = torch.zeros_like(y)[:, pre_len:]

            dec_y = torch.cat(
                [
                    y[:, pre_len-1:pre_len],
                    mask
                ],
                dim=1
            )

            logits = model(x, xt, dec_y, yt)

            loss_mse = mse_loss(
                logits,
                y[:, pre_len:]
            )

            loss_mae = mae_loss(
                logits,
                y[:, pre_len:]
            )

            optimizer.zero_grad()
            loss_mse.backward()
            optimizer.step()

            train_mse += loss_mse.item()
            train_mae += loss_mae.item()

        train_mse /= len(train_loader)
        train_mae /= len(train_loader)

        ########################
        # Validation
        ########################

        model.eval()

        val_mse = 0
        val_mae = 0

        predictions = []
        actual = []

        with torch.no_grad():

            for x, y, xt, yt in test_loader:

                mask = torch.zeros_like(y)[:, pre_len:]

                dec_y = torch.cat(
                    [
                        y[:, pre_len-1:pre_len],
                        mask
                    ],
                    dim=1
                )

                logits = model(
                    x,
                    xt,
                    dec_y,
                    yt
                )

                loss_mse = mse_loss(
                    logits,
                    y[:, pre_len:]
                )

                loss_mae = mae_loss(
                    logits,
                    y[:, pre_len:]
                )

                val_mse += loss_mse.item()
                val_mae += loss_mae.item()

                pred = y_scaler.inverse_transform(
                    logits.numpy().reshape(-1, 1)
                )

                gt = y_scaler.inverse_transform(
                    y[:, pre_len:].numpy().reshape(-1, 1)
                )

                predictions.append(pred)
                actual.append(gt)

        val_mse /= len(test_loader)
        val_mae /= len(test_loader)

        predictions = np.concatenate(
            predictions,
            axis=0
        )

        actual = np.concatenate(
            actual,
            axis=0
        )

        print(
            f"Epoch {epoch+1:3d} | "
            f"Train MSE {train_mse:.6f} | "
            f"Val MSE {val_mse:.6f}"
        )

        if val_mse < best_loss:

            best_loss = val_mse
            best_model = model.state_dict()

    model.load_state_dict(best_model)

    return (
        model,
        predictions,
        actual,
        best_loss,
        x_scaler,
        y_scaler
    )

In [61]:
model, predictions, actual, best_loss, x_scaler, y_scaler = TransformerTrain(
    stock_data,
    s_len=5
)

100%|██████████| 25/25 [00:10<00:00,  2.35it/s]

Epoch   1 | Train MSE 0.254363 | Val MSE 0.008234

100%|██████████| 25/25 [00:09<00:00,  2.67it/s]

Epoch   2 | Train MSE 0.018048 | Val MSE 0.003126

100%|██████████| 25/25 [00:09<00:00,  2.69it/s]

Epoch   3 | Train MSE 0.002534 | Val MSE 0.001256

100%|██████████| 25/25 [00:10<00:00,  2.46it/s]

Epoch   4 | Train MSE 0.000825 | Val MSE 0.001063

100%|██████████| 25/25 [00:10<00:00,  2.44it/s]

Epoch   5 | Train MSE 0.000609 | Val MSE 0.000971

100%|██████████| 25/25 [00:09<00:00,  2.69it/s]

Epoch   6 | Train MSE 0.000480 | Val MSE 0.000853

100%|██████████| 25/25 [00:09<00:00,  2.69it/s]

Epoch   7 | Train MSE 0.000452 | Val MSE 0.000729

100%|██████████| 25/25 [00:10<00:00,  2.47it/s]

Epoch   8 | Train MSE 0.000381 | Val MSE 0.000710

100%|██████████| 25/25 [00:10<00:00,  2.48it/s]

Epoch   9 | Train MSE 0.000347 | Val MSE 0.000682

100%|██████████| 25/25 [00:09<00:00,  2.67it/s]

Epoch  10 | Train MSE 0.000341 | Val MSE 0.000698

100%|██████████| 25/25 [00:09<00:00,  2.69it/s]

Epoch  11 | Train MSE 0.000353 | Val MSE 0.000644

100%|██████████| 25/25 [00:10<00:00,  2.44it/s]

Epoch  12 | Train MSE 0.000335 | Val MSE 0.000685

100%|██████████| 25/25 [00:10<00:00,  2.44it/s]

Epoch  13 | Train MSE 0.000390 | Val MSE 0.000605

100%|██████████| 25/25 [00:09<00:00,  2.75it/s]

Epoch  14 | Train MSE 0.000298 | Val MSE 0.000614

100%|██████████| 25/25 [00:09<00:00,  2.70it/s]

Epoch  15 | Train MSE 0.000287 | Val MSE 0.000565

100%|██████████| 25/25 [00:10<00:00,  2.47it/s]

Epoch  16 | Train MSE 0.000296 | Val MSE 0.000611

100%|██████████| 25/25 [00:10<00:00,  2.44it/s]

Epoch  17 | Train MSE 0.000300 | Val MSE 0.000634

100%|██████████| 25/25 [00:09<00:00,  2.73it/s]

Epoch  18 | Train MSE 0.000302 | Val MSE 0.000607

100%|██████████| 25/25 [00:09<00:00,  2.68it/s]

Epoch  19 | Train MSE 0.000291 | Val MSE 0.000588

100%|██████████| 25/25 [00:10<00:00,  2.48it/s]

Epoch  20 | Train MSE 0.000260 | Val MSE 0.000558

In [63]:
# ==========================
# Hyperparameters
# ==========================

train_size = 0.7
s_len = 5
pre_len = 1

batch_size = 64
lr = 5e-5
epochs = 100


# ==========================
# Sliding Window Generation
# ==========================

def create_data(datas, s_len):

    values = []
    labels = []

    lens = datas.shape[0]
    datas = datas.values

    for index in range(lens - s_len - pre_len):

        value = datas[
            index:index+s_len,
            [stock_data.columns.get_loc('date')] +
            [stock_data.columns.get_loc(col) for col in X]
        ]

        label = datas[
            index+s_len-pre_len:index+s_len+pre_len,
            [
                stock_data.columns.get_loc('date'),
                stock_data.columns.get_loc('Close')
            ]
        ]

        values.append(value)
        labels.append(label)

    return values, labels


# ==========================
# Dataset - Returns (num_features, seq_len)
# ==========================

class AmaData(Dataset):

    def __init__(self, values, labels, x_scaler, y_scaler):

        self.values = values
        self.labels = labels
        self.x_scaler = x_scaler
        self.y_scaler = y_scaler

    def __len__(self):
        return len(self.values)

    def create_time(self, data):

        time = pd.to_datetime(data[:, 0])

        week = np.int32(time.dayofweek)[:, None]
        month = np.int32(time.month)[:, None]
        day = np.int32(time.day)[:, None]

        return np.concatenate([month, week, day], axis=-1)

    def __getitem__(self, idx):

        value = self.values[idx]  # Shape: (seq_len, num_features)
        label = self.labels[idx]  # Shape: (seq_len, 1)

        value_t = self.create_time(value)  # Shape: (seq_len, 3)
        label_t = self.create_time(label)  # Shape: (seq_len, 3)

        # Scale features (remove date column)
        value = self.x_scaler.transform(value[:, 1:])  # Shape: (seq_len, num_features)
        label = self.y_scaler.transform(label[:, 1][:, None])  # Shape: (seq_len, 1)

        # Transpose to (num_features, seq_len)
        value = torch.FloatTensor(value).permute(1, 0)  # (num_features, seq_len)
        label = torch.FloatTensor(label).permute(1, 0)  # (1, seq_len)

        # Time features - transpose to (3, seq_len)
        value_t = torch.LongTensor(value_t).permute(1, 0)  # (3, seq_len)
        label_t = torch.LongTensor(label_t).permute(1, 0)  # (3, seq_len)

        return value, label, value_t, label_t


# ==========================
# Read Data
# ==========================

def read_data(data, s_len):

    values, labels = create_data(data, s_len)

    split_idx = int(len(values) * train_size)

    train_x = values[:split_idx]
    train_y = labels[:split_idx]

    test_x = values[split_idx:]
    test_y = labels[split_idx:]

    x_scaler = MinMaxScaler()
    y_scaler = MinMaxScaler()

    train_features = np.concatenate(
        [x[:, 1:] for x in train_x],
        axis=0
    )

    train_targets = np.concatenate(
        [y[:, 1:] for y in train_y],
        axis=0
    )

    x_scaler.fit(train_features)
    y_scaler.fit(train_targets)

    return (
        train_x,
        test_x,
        train_y,
        test_y,
        x_scaler,
        y_scaler
    )


# ==========================
# Model Definition (Example)
# ==========================

class TransformerModel(nn.Module):
    def __init__(self, num_features, seq_len, d_model, nhead, num_layers, output_size):
        super(TransformerModel, self).__init__()

        self.num_features = num_features
        self.seq_len = seq_len
        self.d_model = d_model

        # Input projection: (num_features, seq_len) -> (num_features, d_model)
        self.input_proj = nn.Linear(seq_len, d_model)

        # Positional encoding
        self.pos_encoding = nn.Parameter(torch.randn(1, num_features, d_model) * 0.1)

        # Transformer encoder
        self.transformer = nn.TransformerEncoder(
            nn.TransformerEncoderLayer(
                d_model=d_model,
                nhead=nhead,
                dim_feedforward=d_model * 4,
                dropout=0.1,
                activation='relu',
                batch_first=True
            ),
            num_layers=num_layers
        )

        # Output projection
        self.output_proj = nn.Linear(d_model, output_size)

    def forward(self, x, xt, dec_y, yt):
        """
        Args:
            x: (batch_size, num_features, seq_len)
            xt: (batch_size, 3, seq_len) - time features
            dec_y: (batch_size, 1, seq_len) - decoder input
            yt: (batch_size, 3, seq_len) - time features for decoder
        Returns:
            (batch_size, 1, seq_len) - predictions
        """
        # x: (batch_size, num_features, seq_len)
        # Project seq_len dimension to d_model
        x = self.input_proj(x)  # (batch_size, num_features, d_model)

        # Add positional encoding
        x = x + self.pos_encoding

        # Pass through transformer
        x = self.transformer(x)  # (batch_size, num_features, d_model)

        # Project to output size
        x = self.output_proj(x)  # (batch_size, num_features, output_size)

        # Take mean across features or use specific feature
        x = x.mean(dim=1, keepdim=True)  # (batch_size, 1, output_size)

        return x


# ==========================
# Training Function (Updated)
# ==========================

def TransformerTrain(data, s_len):

    (
        train_x,
        test_x,
        train_y,
        test_y,
        x_scaler,
        y_scaler
    ) = read_data(data, s_len)

    train_dataset = AmaData(
        train_x,
        train_y,
        x_scaler,
        y_scaler
    )

    test_dataset = AmaData(
        test_x,
        test_y,
        x_scaler,
        y_scaler
    )

    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=batch_size,
        shuffle=False
    )

    # Initialize model
    num_features = len(X)  # Number of feature columns
    d_model = 64
    nhead = 4
    num_layers = 2
    output_size = 1

    model = TransformerModel(
        num_features=num_features,
        seq_len=s_len,
        d_model=d_model,
        nhead=nhead,
        num_layers=num_layers,
        output_size=output_size
    )

    mse_loss = nn.MSELoss()
    mae_loss = nn.L1Loss()

    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=lr
    )

    best_loss = float("inf")
    best_model = None

    for epoch in range(epochs):

        ########################
        # Training
        ########################

        model.train()

        train_mse = 0
        train_mae = 0

        for x, y, xt, yt in tqdm(train_loader):
            # x: (batch_size, num_features, seq_len)
            # y: (batch_size, 1, seq_len)
            # xt: (batch_size, 3, seq_len)
            # yt: (batch_size, 3, seq_len)

            # Create decoder input
            # Use last value of y as start token
            last_val = y[:, :, -1:]  # (batch_size, 1, 1)
            mask = torch.zeros_like(y)  # (batch_size, 1, seq_len)

            # For pre_len=1, we just need to predict one step ahead
            # The decoder input should be the last known value
            dec_y = last_val  # (batch_size, 1, 1)

            # For prediction, we want to predict the next value
            # The target is y[:, :, -pre_len:] or similar
            # Since pre_len=1, target is the last value
            target = y  # (batch_size, 1, seq_len)

            logits = model(x, xt, dec_y, yt)

            # Loss calculation
            loss_mse = mse_loss(
                logits,
                target[:, :, -1:]  # Only predict the last time step
            )

            loss_mae = mae_loss(
                logits,
                target[:, :, -1:]
            )

            optimizer.zero_grad()
            loss_mse.backward()
            optimizer.step()

            train_mse += loss_mse.item()
            train_mae += loss_mae.item()

        train_mse /= len(train_loader)
        train_mae /= len(train_loader)

        ########################
        # Validation
        ########################

        model.eval()

        val_mse = 0
        val_mae = 0

        predictions = []
        actual = []

        with torch.no_grad():

            for x, y, xt, yt in test_loader:

                last_val = y[:, :, -1:]  # (batch_size, 1, 1)
                dec_y = last_val
                target = y

                logits = model(
                    x,
                    xt,
                    dec_y,
                    yt
                )

                loss_mse = mse_loss(
                    logits,
                    target[:, :, -1:]
                )

                loss_mae = mae_loss(
                    logits,
                    target[:, :, -1:]
                )

                val_mse += loss_mse.item()
                val_mae += loss_mae.item()

                # Inverse transform predictions
                # logits: (batch_size, 1, 1)
                pred = y_scaler.inverse_transform(
                    logits.numpy().reshape(-1, 1)
                )

                gt = y_scaler.inverse_transform(
                    target[:, :, -1:].numpy().reshape(-1, 1)
                )

                predictions.append(pred)
                actual.append(gt)

        val_mse /= len(test_loader)
        val_mae /= len(test_loader)

        predictions = np.concatenate(
            predictions,
            axis=0
        )

        actual = np.concatenate(
            actual,
            axis=0
        )

        print(
            f"Epoch {epoch+1:3d} | "
            f"Train MSE {train_mse:.6f} | "
            f"Val MSE {val_mse:.6f}"
        )

        if val_mse < best_loss:

            best_loss = val_mse
            best_model = model.state_dict()

    model.load_state_dict(best_model)

    return (
        model,
        predictions,
        actual,
        best_loss,
        x_scaler,
        y_scaler
    )


# ==========================
# Usage Example
# ==========================

if __name__ == "__main__":
    # Assuming you have your data ready
    # stock_data = your stock data DataFrame
    # X = list of feature column names

    model, predictions, actual, best_loss, x_scaler, y_scaler = TransformerTrain(
        stock_data, s_len
    )

    print(f"Predictions shape: {predictions.shape}")
    print(f"Actual shape: {actual.shape}")
    print(f"Best loss: {best_loss:.6f}")

100%|██████████| 25/25 [00:02<00:00, 10.16it/s]

Epoch   1 | Train MSE 0.069068 | Val MSE 0.093236

100%|██████████| 25/25 [00:02<00:00, 10.41it/s]

Epoch   2 | Train MSE 0.051581 | Val MSE 0.109050

100%|██████████| 25/25 [00:03<00:00,  7.53it/s]

Epoch   3 | Train MSE 0.049772 | Val MSE 0.100952

100%|██████████| 25/25 [00:02<00:00,  9.20it/s]

Epoch   4 | Train MSE 0.047548 | Val MSE 0.084258

100%|██████████| 25/25 [00:02<00:00, 10.53it/s]

Epoch   5 | Train MSE 0.048228 | Val MSE 0.086606

100%|██████████| 25/25 [00:02<00:00, 10.49it/s]

Epoch   6 | Train MSE 0.043979 | Val MSE 0.077770

100%|██████████| 25/25 [00:03<00:00,  8.24it/s]

Epoch   7 | Train MSE 0.040111 | Val MSE 0.095834

100%|██████████| 25/25 [00:02<00:00,  8.58it/s]

Epoch   8 | Train MSE 0.032471 | Val MSE 0.084235

100%|██████████| 25/25 [00:02<00:00, 10.40it/s]

Epoch   9 | Train MSE 0.021511 | Val MSE 0.090979

100%|██████████| 25/25 [00:02<00:00, 10.04it/s]

Epoch  10 | Train MSE 0.013126 | Val MSE 0.092645

100%|██████████| 25/25 [00:02<00:00,  9.18it/s]

Epoch  11 | Train MSE 0.008111 | Val MSE 0.099449

100%|██████████| 25/25 [00:03<00:00,  7.88it/s]

Epoch  12 | Train MSE 0.007317 | Val MSE 0.086135

100%|██████████| 25/25 [00:02<00:00, 10.33it/s]

Epoch  13 | Train MSE 0.006071 | Val MSE 0.070033

100%|██████████| 25/25 [00:03<00:00,  7.74it/s]

Epoch  14 | Train MSE 0.005732 | Val MSE 0.062598

100%|██████████| 25/25 [00:02<00:00,  8.52it/s]

Epoch  15 | Train MSE 0.005177 | Val MSE 0.066359

100%|██████████| 25/25 [00:03<00:00,  7.95it/s]

Epoch  16 | Train MSE 0.005052 | Val MSE 0.056812

100%|██████████| 25/25 [00:02<00:00, 10.43it/s]

Epoch  17 | Train MSE 0.004532 | Val MSE 0.065937

100%|██████████| 25/25 [00:02<00:00, 10.06it/s]

Epoch  18 | Train MSE 0.004410 | Val MSE 0.058841

100%|██████████| 25/25 [00:02<00:00,  9.53it/s]

Epoch  19 | Train MSE 0.004073 | Val MSE 0.050045

100%|██████████| 25/25 [00:03<00:00,  7.50it/s]

Epoch  20 | Train MSE 0.004077 | Val MSE 0.056290

100%|██████████| 25/25 [00:02<00:00, 10.43it/s]

Epoch  21 | Train MSE 0.003959 | Val MSE 0.040728

100%|██████████| 25/25 [00:02<00:00, 10.43it/s]

Epoch  22 | Train MSE 0.003963 | Val MSE 0.052719

100%|██████████| 25/25 [00:02<00:00, 10.48it/s]

Epoch  23 | Train MSE 0.003452 | Val MSE 0.053134

100%|██████████| 25/25 [00:03<00:00,  7.34it/s]

Epoch  24 | Train MSE 0.003695 | Val MSE 0.041749

100%|██████████| 25/25 [00:02<00:00, 10.28it/s]

Epoch  25 | Train MSE 0.003554 | Val MSE 0.045501

100%|██████████| 25/25 [00:02<00:00, 10.33it/s]

Epoch  26 | Train MSE 0.003504 | Val MSE 0.060600

100%|██████████| 25/25 [00:02<00:00, 10.15it/s]

Epoch  27 | Train MSE 0.003657 | Val MSE 0.053965

100%|██████████| 25/25 [00:03<00:00,  7.38it/s]

Epoch  28 | Train MSE 0.003168 | Val MSE 0.046177

100%|██████████| 25/25 [00:02<00:00,  9.69it/s]

Epoch  29 | Train MSE 0.003065 | Val MSE 0.043228

100%|██████████| 25/25 [00:02<00:00, 10.39it/s]

Epoch  30 | Train MSE 0.002724 | Val MSE 0.038259

100%|██████████| 25/25 [00:02<00:00, 10.28it/s]

Epoch  31 | Train MSE 0.003158 | Val MSE 0.044133

100%|██████████| 25/25 [00:03<00:00,  7.97it/s]

Epoch  32 | Train MSE 0.002866 | Val MSE 0.040391

100%|██████████| 25/25 [00:02<00:00,  8.87it/s]

Epoch  33 | Train MSE 0.003098 | Val MSE 0.047552

100%|██████████| 25/25 [00:02<00:00, 10.32it/s]

Epoch  34 | Train MSE 0.002777 | Val MSE 0.040194

100%|██████████| 25/25 [00:02<00:00, 10.48it/s]

Epoch  35 | Train MSE 0.002754 | Val MSE 0.043805

100%|██████████| 25/25 [00:02<00:00,  8.63it/s]

Epoch  36 | Train MSE 0.002807 | Val MSE 0.037744

100%|██████████| 25/25 [00:03<00:00,  8.24it/s]

Epoch  37 | Train MSE 0.002496 | Val MSE 0.043974

100%|██████████| 25/25 [00:02<00:00, 10.39it/s]

Epoch  38 | Train MSE 0.002487 | Val MSE 0.039652

100%|██████████| 25/25 [00:02<00:00, 10.58it/s]

Epoch  39 | Train MSE 0.002403 | Val MSE 0.037382

100%|██████████| 25/25 [00:02<00:00,  9.82it/s]

Epoch  40 | Train MSE 0.002450 | Val MSE 0.040619

100%|██████████| 25/25 [00:03<00:00,  7.39it/s]

Epoch  41 | Train MSE 0.002668 | Val MSE 0.040018

100%|██████████| 25/25 [00:02<00:00, 10.33it/s]

Epoch  42 | Train MSE 0.002529 | Val MSE 0.031224

100%|██████████| 25/25 [00:02<00:00, 10.54it/s]

Epoch  43 | Train MSE 0.002642 | Val MSE 0.036883

100%|██████████| 25/25 [00:02<00:00, 10.48it/s]

Epoch  44 | Train MSE 0.002325 | Val MSE 0.039896

100%|██████████| 25/25 [00:03<00:00,  7.42it/s]

Epoch  45 | Train MSE 0.002217 | Val MSE 0.035948

100%|██████████| 25/25 [00:02<00:00, 10.30it/s]

Epoch  46 | Train MSE 0.002338 | Val MSE 0.041184

100%|██████████| 25/25 [00:02<00:00, 10.21it/s]

Epoch  47 | Train MSE 0.002217 | Val MSE 0.034315

100%|██████████| 25/25 [00:02<00:00, 10.42it/s]

Epoch  48 | Train MSE 0.002210 | Val MSE 0.039723

100%|██████████| 25/25 [00:03<00:00,  7.64it/s]

Epoch  49 | Train MSE 0.002180 | Val MSE 0.035946

100%|██████████| 25/25 [00:02<00:00,  9.72it/s]

Epoch  50 | Train MSE 0.002048 | Val MSE 0.036994

100%|██████████| 25/25 [00:02<00:00, 10.04it/s]

Epoch  51 | Train MSE 0.002170 | Val MSE 0.038132

100%|██████████| 25/25 [00:02<00:00, 10.44it/s]

Epoch  52 | Train MSE 0.002170 | Val MSE 0.033115

100%|██████████| 25/25 [00:03<00:00,  8.18it/s]

Epoch  53 | Train MSE 0.002069 | Val MSE 0.038771

100%|██████████| 25/25 [00:02<00:00,  8.35it/s]

Epoch  54 | Train MSE 0.001920 | Val MSE 0.031728

100%|██████████| 25/25 [00:02<00:00, 10.23it/s]

Epoch  55 | Train MSE 0.002001 | Val MSE 0.036367

100%|██████████| 25/25 [00:02<00:00, 10.37it/s]

Epoch  56 | Train MSE 0.001865 | Val MSE 0.040345

100%|██████████| 25/25 [00:02<00:00,  8.58it/s]

Epoch  57 | Train MSE 0.001961 | Val MSE 0.028246

100%|██████████| 25/25 [00:03<00:00,  7.63it/s]

Epoch  58 | Train MSE 0.001923 | Val MSE 0.041908

100%|██████████| 25/25 [00:02<00:00,  9.96it/s]

Epoch  59 | Train MSE 0.001912 | Val MSE 0.030926

100%|██████████| 25/25 [00:02<00:00, 10.05it/s]

Epoch  60 | Train MSE 0.001945 | Val MSE 0.037506

100%|██████████| 25/25 [00:02<00:00,  9.09it/s]

Epoch  61 | Train MSE 0.001857 | Val MSE 0.035297

100%|██████████| 25/25 [00:03<00:00,  7.35it/s]

Epoch  62 | Train MSE 0.001813 | Val MSE 0.032798

100%|██████████| 25/25 [00:02<00:00, 10.02it/s]

Epoch  63 | Train MSE 0.001812 | Val MSE 0.029980

100%|██████████| 25/25 [00:02<00:00,  9.90it/s]

Epoch  64 | Train MSE 0.001747 | Val MSE 0.034634

100%|██████████| 25/25 [00:02<00:00,  9.65it/s]

Epoch  65 | Train MSE 0.001749 | Val MSE 0.029346

100%|██████████| 25/25 [00:03<00:00,  7.03it/s]

Epoch  66 | Train MSE 0.001779 | Val MSE 0.031968

100%|██████████| 25/25 [00:02<00:00, 10.06it/s]

Epoch  67 | Train MSE 0.001733 | Val MSE 0.038119

100%|██████████| 25/25 [00:02<00:00,  9.95it/s]

Epoch  68 | Train MSE 0.001729 | Val MSE 0.028906

100%|██████████| 25/25 [00:02<00:00, 10.33it/s]

Epoch  69 | Train MSE 0.001505 | Val MSE 0.036067

100%|██████████| 25/25 [00:03<00:00,  7.21it/s]

Epoch  70 | Train MSE 0.001645 | Val MSE 0.034929

100%|██████████| 25/25 [00:02<00:00,  9.94it/s]

Epoch  71 | Train MSE 0.001636 | Val MSE 0.028877

100%|██████████| 25/25 [00:02<00:00,  9.91it/s]

Epoch  72 | Train MSE 0.001703 | Val MSE 0.031716

100%|██████████| 25/25 [00:02<00:00,  9.99it/s]

Epoch  73 | Train MSE 0.001549 | Val MSE 0.034081

100%|██████████| 25/25 [00:03<00:00,  6.97it/s]

Epoch  74 | Train MSE 0.001524 | Val MSE 0.028954

100%|██████████| 25/25 [00:02<00:00,  9.76it/s]

Epoch  75 | Train MSE 0.001479 | Val MSE 0.031887

100%|██████████| 25/25 [00:02<00:00,  9.89it/s]

Epoch  76 | Train MSE 0.001559 | Val MSE 0.027920

100%|██████████| 25/25 [00:02<00:00, 10.06it/s]

Epoch  77 | Train MSE 0.001577 | Val MSE 0.030559

100%|██████████| 25/25 [00:03<00:00,  7.26it/s]

Epoch  78 | Train MSE 0.001472 | Val MSE 0.031010

100%|██████████| 25/25 [00:02<00:00,  9.95it/s]

Epoch  79 | Train MSE 0.001407 | Val MSE 0.026977

100%|██████████| 25/25 [00:02<00:00, 10.06it/s]

Epoch  80 | Train MSE 0.001569 | Val MSE 0.034321

100%|██████████| 25/25 [00:02<00:00, 10.26it/s]

Epoch  81 | Train MSE 0.001504 | Val MSE 0.028834

100%|██████████| 25/25 [00:03<00:00,  7.75it/s]

Epoch  82 | Train MSE 0.001502 | Val MSE 0.029330

100%|██████████| 25/25 [00:02<00:00,  8.84it/s]

Epoch  83 | Train MSE 0.001510 | Val MSE 0.030629

100%|██████████| 25/25 [00:02<00:00, 10.06it/s]

Epoch  84 | Train MSE 0.001578 | Val MSE 0.024831

100%|██████████| 25/25 [00:02<00:00, 10.12it/s]

Epoch  85 | Train MSE 0.001505 | Val MSE 0.029181

100%|██████████| 25/25 [00:03<00:00,  8.14it/s]

Epoch  86 | Train MSE 0.001347 | Val MSE 0.026408

100%|██████████| 25/25 [00:03<00:00,  8.18it/s]

Epoch  87 | Train MSE 0.001375 | Val MSE 0.032193

100%|██████████| 25/25 [00:02<00:00, 10.08it/s]

Epoch  88 | Train MSE 0.001544 | Val MSE 0.024449

100%|██████████| 25/25 [00:02<00:00, 10.01it/s]

Epoch  89 | Train MSE 0.001446 | Val MSE 0.024995

100%|██████████| 25/25 [00:02<00:00,  8.53it/s]

Epoch  90 | Train MSE 0.001216 | Val MSE 0.030503

100%|██████████| 25/25 [00:03<00:00,  7.76it/s]

Epoch  91 | Train MSE 0.001345 | Val MSE 0.027273

100%|██████████| 25/25 [00:02<00:00, 10.03it/s]

Epoch  92 | Train MSE 0.001282 | Val MSE 0.026642

100%|██████████| 25/25 [00:02<00:00,  9.48it/s]

Epoch  93 | Train MSE 0.001359 | Val MSE 0.027206

100%|██████████| 25/25 [00:02<00:00,  8.61it/s]

Epoch  94 | Train MSE 0.001340 | Val MSE 0.030627

100%|██████████| 25/25 [00:03<00:00,  7.52it/s]

Epoch  95 | Train MSE 0.001345 | Val MSE 0.025262

100%|██████████| 25/25 [00:02<00:00, 10.02it/s]

Epoch  96 | Train MSE 0.001254 | Val MSE 0.029395

100%|██████████| 25/25 [00:02<00:00, 10.06it/s]

Epoch  97 | Train MSE 0.001204 | Val MSE 0.028118

100%|██████████| 25/25 [00:02<00:00,  9.22it/s]

Epoch  98 | Train MSE 0.001224 | Val MSE 0.021498

100%|██████████| 25/25 [00:03<00:00,  7.20it/s]

Epoch  99 | Train MSE 0.001274 | Val MSE 0.030432

100%|██████████| 25/25 [00:02<00:00, 10.16it/s]

Epoch 100 | Train MSE 0.001231 | Val MSE 0.025934
Predictions shape: (663, 1)
Actual shape: (663, 1)
Best loss: 0.021498